name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
          echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'